source 'http://rubygems.org'
ruby '2.3.3'

gem 'cucumber'
gem 'sinatra'
gem 'rspec-sinatra'
gem 'selenium-webdriver'
gem 'shotgun'
gem 'rubocop-rspec'
gem 'rubocop'
gem 'coveralls'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'database_cleaner'
gem 'rack'
gem 'rake'
gem 'bcrypt'
gem 'sinatra-flash'
gem 'dm-migrations'

group :test do
  gem 'rspec'
  gem 'capybara'
